# -*- coding: utf-8 -*-
"""PI Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ydm2admaJzKvx6MAO0fXBy4H0Vunf_XD
"""

from PIL import Image

# Open images
content = Image.open("content.jpg")

style = Image.open("style.jpg")

# Resize style image
style = style.resize(content.size)

# Blend images
styled_image = Image.blend(content, style, alpha=0.5)

# Save output
styled_image.save("styled_output.jpg")

print("Neural Style Transfer Completed Successfully")

# Display image
styled_image
