# -*- coding: utf-8 -*-
"""PI Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ydm2admaJzKvx6MAO0fXBy4H0Vunf_XD
"""

!pip install diffusers transformers accelerate torch safetensors

from diffusers import StableDiffusionPipeline
import torch

# Load model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

# Prompt
prompt = "A futuristic city at night with neon lights"

# Generate image
image = pipe(prompt).images[0]

# Save image
image.save("generated_image.png")

# Display image
image